### PR TITLE
Change buildUrl to support https

### PR DESCRIPTION
**Pull request by JellyBool**
Add an argument to buildUrl to make it support https

### CODE REVIEW

**Comment by longbai** [comment]
@JellyBool :+1:  LGTM

**Comment by longbai** [comment]
@JellyBool :+1:  LGTM

**Comment by longbai** [comment]
@JellyBool :+1:  LGTM, 不过麻烦 调整下代码格式，CI  不过 :)

**Comment by longbai** [comment]
@JellyBool :+1:  LGTM, 不过麻烦 调整下代码格式，CI  不过 :)

**Comment by longbai** [comment]
@JellyBool :+1:  LGTM, 不过麻烦 调整下代码格式，CI  不过 :)
FILE: ...me/travis/build/qiniu/php-sdk/src/Qiniu/Processing/Operation.php

| [x] Expected 1 space between comma and argument
    |       |     "$protocol"; 0 found

**Comment by JellyBool** [comment]
@longbai 不好意思，之前手滑。。。

**Pull request merged**
